/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pmsm_phi_e_constraint_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s3[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s4[5] = {0, 2, 0, 0, 0};
static const casadi_int casadi_s5[10] = {6, 3, 0, 0, 2, 4, 4, 5, 4, 5};
static const casadi_int casadi_s6[10] = {2, 3, 0, 2, 3, 4, 0, 1, 0, 1};

/* pmsm_phi_e_constraint:(i0[2],i1[],i2[],i3[4])->(o0[2],o1[2x2],o2[0x2],o3[6x3,4nz],o4[2x3,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][3] : 0;
  a1=7.5000000000000000e+00;
  a2=-4.2999999999999988e-05;
  a3=arg[0]? arg[0][0] : 0;
  a4=(a2*a3);
  a5=arg[0]? arg[0][1] : 0;
  a6=(a4*a5);
  a7=1.3800000000000000e-02;
  a8=(a7*a5);
  a6=(a6+a8);
  a6=(a1*a6);
  a0=(a0-a6);
  if (res[0]!=0) res[0][0]=a0;
  a0=3.2942249999999996e-04;
  a6=1.1449000000000000e-08;
  a8=arg[3]? arg[3][0] : 0;
  a9=casadi_sq(a8);
  a6=(a6*a9);
  a6=(a0+a6);
  a9=casadi_sq(a3);
  a9=(a6*a9);
  a10=2.2499999999999996e-08;
  a11=casadi_sq(a8);
  a10=(a10*a11);
  a0=(a0+a10);
  a10=casadi_sq(a5);
  a10=(a0*a10);
  a9=(a9+a10);
  a10=3.6299999999999999e-02;
  a11=(a10*a8);
  a11=(a2*a11);
  a12=(a11*a3);
  a13=(a12*a5);
  a9=(a9+a13);
  a13=1.0700000000000000e-04;
  a14=2.;
  a15=casadi_sq(a8);
  a15=(a14*a15);
  a13=(a13*a15);
  a13=(a7*a13);
  a15=(a13*a3);
  a9=(a9+a15);
  a10=(a10*a8);
  a10=(a7*a10);
  a15=(a10*a5);
  a9=(a9+a15);
  a15=1.9044000000000000e-04;
  a8=casadi_sq(a8);
  a15=(a15*a8);
  a9=(a9+a15);
  if (res[0]!=0) res[0][1]=a9;
  a9=(a2*a5);
  a9=(a1*a9);
  a9=(-a9);
  if (res[1]!=0) res[1][0]=a9;
  a9=(a4+a7);
  a9=(a1*a9);
  a9=(-a9);
  if (res[1]!=0) res[1][1]=a9;
  a3=(a3+a3);
  a3=(a6*a3);
  a9=(a5*a11);
  a3=(a3+a9);
  a3=(a3+a13);
  if (res[1]!=0) res[1][2]=a3;
  a3=(a5+a5);
  a3=(a0*a3);
  a3=(a3+a12);
  a3=(a3+a10);
  if (res[1]!=0) res[1][3]=a3;
  a6=(a14*a6);
  if (res[3]!=0) res[3][0]=a6;
  if (res[3]!=0) res[3][1]=a11;
  if (res[3]!=0) res[3][2]=a11;
  a14=(a14*a0);
  if (res[3]!=0) res[3][3]=a14;
  a2=(a2*a5);
  a2=(a1*a2);
  a2=(-a2);
  if (res[4]!=0) res[4][0]=a2;
  a4=(a4+a7);
  a1=(a1*a4);
  a1=(-a1);
  if (res[4]!=0) res[4][1]=a1;
  a1=1.;
  if (res[4]!=0) res[4][2]=a1;
  if (res[4]!=0) res[4][3]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int pmsm_phi_e_constraint(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pmsm_phi_e_constraint_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pmsm_phi_e_constraint_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pmsm_phi_e_constraint_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pmsm_phi_e_constraint_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pmsm_phi_e_constraint_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pmsm_phi_e_constraint_incref(void) {
}

CASADI_SYMBOL_EXPORT void pmsm_phi_e_constraint_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pmsm_phi_e_constraint_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pmsm_phi_e_constraint_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real pmsm_phi_e_constraint_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pmsm_phi_e_constraint_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pmsm_phi_e_constraint_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pmsm_phi_e_constraint_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pmsm_phi_e_constraint_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pmsm_phi_e_constraint_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
